@startuml
'https://plantuml.com/activity-diagram-beta

<style>
    usecase {
        BackGroundColor white
        LineThickness 2
    }
    interface {
        BackGroundColor black
        LineThickness 2
        LineColor black
    }
</style>

interface in
interface out

in        .[#black]right.> (process)
(process) .[#black]right.> out

@enduml
