@startuml
'https://plantuml.com/activity-diagram-beta

split
    -[hidden]->
    :Fill;
    :lock buffer;
    if( free space "">="" data size ) then (yes)
        :write data;
    else (no)
    endif
    :unlock buffer;
    end
split again
    -[hidden]->
    :Drain;
    :lock buffer;
    if( buffer data "">="" requested ) then (yes)
        :read data;
    else (no)
    endif
    :unlock buffer;
    end
end split

@enduml
