@startuml
'https://plantuml.com/activity-diagram-beta

split
    -[hidden]->
    :Fill;
    :lock buffer;
    if( free space "">="" data size ) then (yes)
        :write data;
        :signal: ""<color green>ready</color>"";
    else (no)
    endif
    :unlock buffer;
    end
split again
    -[hidden]->
    :Drain;
    :lock buffer;
    if( is buffer empty? ) then (yes)
        :wait for signal: ""<color green>ready</color>"";
    else (no)
    endif
    if( buffer data "">="" requested ) then (yes)
        :read data;
    else (no)
    endif
    :unlock buffer;
    end
end split

@enduml
