@startuml

skinparam linetype ortho
'skinparam linetype polyline
'skinparam monochrome true

skinparam class {
	BackgroundColor white
	ArrowColor black
	BorderColor grey
}

'class Object

class Deleter {
    - _pool_ptr : std::weak_ptr<ObjectPool*>
    + Deleter( pool_ptr : std::weak_ptr<ObjectPool*>> )
    + operator()( object_ptr : Object *)
}

class ObjectPool {
    - _pool : std::stack<std::unique_ptr<Object>>
    + ObjectPool( size : unsigned )
    + acquire() : std::unique_ptr<Object, Deleter>
    + release( o : std::unique_ptr<Object> ) : void
    + release( o : std::unique_ptr<Object, Deleter> ) : void
}

ObjectPool -right-> Deleter
'Object -* ObjectPool

@enduml