@startuml

skinparam linetype ortho
'skinparam linetype polyline
'skinparam monochrome true

skinparam class {
	BackgroundColor white
	ArrowColor black
	BorderColor grey
}

class Client

class Object

class ObjectPool {
    + ObjectPool( size : unsigned )
    + acquire() : Object
    + release( o : Object ) : void
}

Object -* ObjectPool
Client -right-> Object
Client -right-> ObjectPool

@enduml