@startuml

skinparam linetype ortho
'skinparam linetype polyline
'skinparam monochrome true

skinparam class {
	BackgroundColor white
	ArrowColor black
	BorderColor grey
}

class Singleton {
    - instance : Singleton
    ..
    - Singleton()
    + getInstance() : Singleton
}

Singleton -> Singleton

@enduml