@startuml

interface "Radio Browser API" as RadioBrowserAPI
interface "Radio Stream" as RadioStream #back:black;line:black
interface "Sound out" as out #back:black;line:black
RadioBrowserAPI )-right- [NetworkUtils] : http/s
RadioStream .[#black].> [RadioPlayer]
[NetworkUtils].[#black]right.>[RadioBrowser] : raw data
[RadioBrowser].[#black]left.>[NetworkUtils] : query
[RadioBrowser].[#black]right.> [RadioPlayer] : radio station / info
[RadioPlayer] .[#black]right.> out

note bottom of RadioBrowser : Gets a radio station's info from\n the Radio Browser web API
note bottom of RadioPlayer : Plays radio stream
note bottom of NetworkUtils : Network related\nfunctionality

@enduml