@startuml
'https://plantuml.com/class-diagram

class WindowProperty_t {
    + rows : int
    + cols : int
    + pos_y : int
    + pos_x : int
}

class BorderWin_t {
    window : WINDOW *
    panel : PANEL *
    colour : int
}

interface BorderWin {
    + create( int colour ) : BorderWin_t
    + init( BorderWin_t * border_win, WindowProperty_t * property, const char * title ) : bool
    + show( BorderWin_t * border_win ) : bool
    + hide( BorderWin_t * border_win ) : bool
    + free( BorderWin_t * border_win ) : void
}

BorderWin -left-> BorderWin_t
BorderWin -right-> WindowProperty_t

@enduml