@startuml
'https://plantuml.com/component-diagram

skinparam linetype ortho
'skinparam linetype polyline

package ui #lightgrey {
    component UI

    package widget #white {
        component BorderWin
        component ScrollBar
        component SlideMenu
        component Dialog
        component ScrollWin

        Dialog    *-- ScrollWin
        Dialog    *-- ScrollBar
        Dialog    *-left- BorderWin
        SlideMenu *-- ScrollBar
    }

    package window #white {
        component RSListWin
        component BrowserWin

        BrowserWin *-left- RSListWin
    }

    package dialog #white {
        component ContextHelp
        component RSFind
        component RSInfo
        component RSEdit
        component OptionsMenu

        ContextHelp *-- Dialog
    }

    BrowserWin  *-- SlideMenu
    OptionsMenu *-- SlideMenu
    RSFind      *-- Dialog
    RSInfo      *-- Dialog
    RSEdit      *-- Dialog
    OptionsMenu *-- BorderWin

    UI      --> OptionsMenu
    UI      --> ContextHelp
    UI      --> RSFind
    UI      --> RSInfo
    UI      --> RSEdit
    UI      --> RSListWin
    UI      --> BrowserWin
}

@enduml