@startmindmap

<style>
    node {
        LineColor honeydew
        BackgroundColor honeydew
        Shadowing 100.0
    }

    rootNode {
        LineColor black
        BackgroundColor thistle
        LineThickness 2.0
        RoundCorner 10
        Shadowing 100.0
    }

    :depth(1) {
        BackgroundColor lightcoral
        LineColor lightcoral
    }

    .help {
        LineColor dodgerblue
        BackgroundColor APPLICATION
    }

    .info {
        LineColor mediumseagreen
        BackgroundColor TECHNOLOGY
    }

    .search {
        LineColor orangered
        BackgroundColor orange
    }

    .edit {
        LineColor mediumorchid
        BackgroundColor violet
    }

    .options {
        LineColor gold
        BackgroundColor floralwhite
    }

    arrow {
        LineStyle 0
        LineThickness 1.5
        LineColor mediumpurple
    }
</style>

* cTune\n(<color purple>""UI""</color>)
** "Favourites" tab\n(<color purple>""RSListWin""</color>)
*** Add new station\n(<color purple>""RSEdit""</color> dialog) <<edit>>
**** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>
*** Edit selected station\n(<color purple>""RSEdit""</color> dialog) <<edit>>
**** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>
*** View queued station info\n(<color purple>""RSInfo""</color> dialog) <<info>>
**** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>
*** View selected station info\n(<color purple>""RSInfo""</color> dialog) <<info>>
**** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>
*** Search for station\n(<color purple>""RSFind""</color> dialog) <<search>>
**** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>
*** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>
*** Options menu\n(<color purple>""OptionsMenu""</color> dialog) <<options>>
**** Add new station\n(<color purple>""RSEdit""</color> dialog) <<edit>>
***** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>
**** Edit selected station\n(<color purple>""RSEdit""</color> dialog) <<edit>>
***** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>
left side
** "Search" tab\n(<color purple>""RSListWin""</color>)
*** View selected station info\n(<color purple>""RSInfo""</color> dialog) <<info>>
**** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>
*** View queued station info\n(<color purple>""RSInfo""</color> dialog) <<info>>
**** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>
*** Search for station\n(<color purple>""RSFind""</color> dialog) <<search>>
**** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>
*** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>
** "Browser" tab\n(<color purple>""BrowserWin""</color>)
*** View selected station info\n(<color purple>""RSInfo""</color> dialog) <<info>>
**** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>
*** View queued station info\n(<color purple>""RSInfo""</color> dialog) <<info>>
**** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>
*** Search for station\n(<color purple>""RSFind""</color> dialog) <<search>>
**** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>
*** Show contextual help\n(<color purple>""ContextHelp""</color> dialog) <<help>>

@endmindmap
