@startuml
'https://plantuml.com/component-diagram

package widget #white {
    component BorderWin
    component ScrollBar
    component SlideMenu
    component Dialog
    component ScrollWin

    Dialog    *-- ScrollWin
    Dialog    *-- ScrollBar
    Dialog    *-- BorderWin
    SlideMenu *-- ScrollBar
}

@enduml