@startuml
'https://plantuml.com/component-diagram

'skinparam ParticipantPadding 10

participant Logger
queue LogQueue
    box "worker thread"
    participant LogWriter
end box
participant "ctune.log" as out

activate Logger
activate LogQueue
-> Logger : ""CTUNE_LOG(..)""
hnote over LogWriter : idle
Logger   -> LogQueue : queue message
deactivate Logger

LogQueue -> LogWriter ++ : ""resume()""
LogWriter -> LogWriter ++ #deepskyblue : wakeup and\nreset timeout

loop while ""!LogQueue.empty()"" and ""timeout > 0""
    LogWriter -> LogQueue  ++ #lightblue : dequeue message
    LogWriter <-- LogQueue --++ #lightblue : message dequeued
    LogWriter -> out -- : write message to file
end
LogWriter -> LogWriter -- : sleep

deactivate LogWriter
|||
hnote over LogWriter : idle

@enduml