@startuml
'https://plantuml.com/class-diagram

hide enum members

enum TextID_e

interface "Language interface" as iLanguage {
    <b>UI global</b>
    ----
    + text( TextID_e text_id ) : const char *
}

iLanguage -down-> TextID_e

@enduml