@startuml
'https://plantuml.com/class-diagram

class RadioStationInfo_t
hide RadioStationInfo_t members

enum PanelID_e {
    PANEL_TITLE = 0
    PANEL_STATUS_1
    PANEL_STATUS_2
    PANEL_STATUS_3
    PANEL_MSG_LINE
    PANEL_FAVOURITES
    PANEL_SEARCH
    PANEL_BROWSER
}

class UI {
    <b>Management</b>
    ----
    + setup( bool show_cursor ) : bool
    + start( void ) : void
    + teardown( void ) : void
    + resize() : void
    + show( enum PanelID panel ) : void
    ----
    <b>Actions (mostly used as callbacks)</b>
    ----
    + setCurrStation( const RadioStationInfo_t * rsi ) : void
    + printSongInfo( const char * str ) : void
    + printVolume( const int vol ) : void
    + printPlaybackState( const bool state ) : void
    + printSearchingState( const bool state ) : void
    + printError( const char * err_str, int err_no ) : void
    + printStatusMsg( const char * info_str ) : void
    ----
    <b>Callback setter</b>
    ----
    + setQuietVolChangeCallback( int(* cb)( int ) ) : void
}

UI --> PanelID_e
UI --> RadioStationInfo_t

@enduml