@startuml
'https://plantuml.com/activity-diagram-beta
'!pragma useVerticalIf on
!pragma useVerticalSwitch on
'skinparam ConditionEndStyle hline

start
:""CLI.processArgs( argc, argv )"";
if( ""parseArgs(..)"" ) then (false)
    #orangered:""CLI_EXIT_ERR"";|
    stop
else (true)
    repeat
        :pack actionable options into list;
        if( ""CLI_ARG_VERSION"" ) then (yes)
            : print version info;
            #lightgreen:""CLI_EXIT_OK"";|
            stop
        elseif( ""CLI_ARG_HELP"" ) then (yes)
            :print usage;
            #lightgreen:""CLI_EXIT_OK"";|
            stop
        elseif( ""CLI_ARG_DEBUG"" ) then (yes)
            :add to actionable list;
        elseif( ""CLI_ARG_FAVOURITE"" ) then (yes)
            :add to actionable list;
        elseif( ""CLI_ARG_PLAY"" ) then (yes)
            :add to actionable list;
        elseif( ""CLI_ARG_RESUME_PLAYBACK"" ) then (yes)
            :add to actionable list;
        elseif( ""CLI_ARG_SHOW_CURSOR"" ) then (yes)
            :add to actionable list;
        else
            #orangered:""CLI_EXIT_ERR"";|
            stop
        endif
    repeat while( more options )
    if( actionable list is empty )
        #lightgreen:""CLI_CONTINUE"";|
        stop
    else
        #lightgreen:""CLI_CONTINUE_WITH_OPT"";|
        stop
    endif
@enduml
