@startuml
'https://plantuml.com/class-diagram

interface RadioBrowser {
    <b>Needed</b>
    ....
    + downloadStations( const RadioBrowserFilter_t * filter, Vector_t * radio_stations ) : bool
    + downloadStationsBy( const ByCategory_e category, const char * search_term, Vector_t * radio_stations ) : bool
    + downloadCategoryItems( const ListCategory_e category, const  RadioBrowserFilter_t * filter, Vector_t * categories ) : bool
    + stationClickCounter( const char * station_uuid,  ClickCounter_t * click_counter ) : bool
    ----
    <b>Optional</b>
    ....
    + downloadServerStats( ServerStats_t * stats ) : bool
    + downloadServerConfig( ServerConfig_t * srv_cfg ) : bool
    + voteForStation( const char * station_uuid,  RadioStationVote_t * vote_state ) : bool
    + addNewStation( NewRadioStation_t * new_station ) : bool
}

enum ByCategory_e {
    RADIOBROWSER_STATION_BY_UUID = 0
    RADIOBROWSER_STATION_BY_NAME
    RADIOBROWSER_STATION_BY_NAME_EXACT
    RADIOBROWSER_STATION_BY_CODEC
    RADIOBROWSER_STATION_BY_CODEC_EXACT
    RADIOBROWSER_STATION_BY_COUNTRY
    RADIOBROWSER_STATION_BY_COUNTRY_EXACT
    RADIOBROWSER_STATION_BY_COUNTRY_CODE_EXACT
    RADIOBROWSER_STATION_BY_STATE
    RADIOBROWSER_STATION_BY_STATE_EXACT
    RADIOBROWSER_STATION_BY_LANGUAGE
    RADIOBROWSER_STATION_BY_LANGUAGE_EXACT
    RADIOBROWSER_STATION_BY_TAG
    RADIOBROWSER_STATION_BY_TAG_EXACT
    RADIOBROWSER_STATION_BY_URL
    RADIOBROWSER_STATION_BY_CLICKS
    RADIOBROWSER_STATION_BY_VOTES
    RADIOBROWSER_STATION_BY_RECENT_CLICKS
    RADIOBROWSER_STATION_BY_RECENT_ADD_OR_MOD
}

enum ListCategory_e {
    RADIOBROWSER_CATEGORY_COUNTRIES = 0
    RADIOBROWSER_CATEGORY_COUNTRYCODES = 1
    RADIOBROWSER_CATEGORY_CODECS = 2
    RADIOBROWSER_CATEGORY_STATES = 3
    RADIOBROWSER_CATEGORY_LANGUAGES = 4
    RADIOBROWSER_CATEGORY_TAGS = 5
}

RadioBrowser --> ByCategory_e
RadioBrowser --> ListCategory_e
@enduml