@startuml
'https://plantuml.com/class-diagram

allowmixing

class Settings {
    - xdg.fallback_data_path : const char *
    - xdg.const char * fallback_cfg_path : const char *
    - xdg.resolved_data_path : String_t
    - xdg.resolved_cfg_path : String_t
    ----
    - favourites.dir_name : const char *
    - favourites.file_name : const char *
    - favourites.favs : HashMap_t[CTUNE_STATIONSRC_COUNT]
    - favourites.sort_id : RadioStationInfo_SortBy_e
    ----
    - config.loaded : bool
    - config.resume_volume ; int
    - config.play_log_overwrite : bool
    - config.timeout_stream_val : int
    - config.timeout_network_val : int
    - config.ui : UIConfig_t
    ----
    - last_station.uuid : String_t
    - last_station.src : StationSrc_e
    ====
    <b>XDG paths</b>
    ----
    + xdg.resolveCfgFilePath( const char * file_name, String_t * resolved_path ) : void
    + xdg.resolveDataFilePath( const char * file_name, String_t * resolved_path ) : void
    ----
    <b>Favourite stations</b>
    ----
    + favs.loadFavourites( void ) : bool
    + favs.saveFavourites( void ) : bool
    + favs.refreshView( Vector_t * stations ) : bool
    + favs.setSortingAttribute( RadioStationInfo_SortBy_e attr ) : void
    + favs.isFavourite( const char * uuid, StationSrc_e src ) : bool
    + favs.getFavourite( const char * uuid, StationSrc_e src ) : const RadioStationInfo_t *
    + favs.addStation( const RadioStationInfo_t * rsi, StationSrc_e src ) : bool
    + favs.removeStation( const RadioStationInfo_t * rsi, StationSrc_e src ) : bool
    ----
    <b>Application configuration</b>
    ----
    + cfg.loadCfg)( void ) : bool
    + cfg.isLoaded( void ) : bool
    + cfg.writeCfg( void ) : bool
    + cfg.getVolume( void ) : int
    + cfg.setVolume( int ) : int
    + cfg.modVolume( int ) : int
    + cfg.getLastPlayedUUID( void ) : const char *
    + cfg.getLastPlayedSrc( void ) : StationSrc_e
    + cfg.setLastPlayedStation( const char *, StationSrc_e ) : void
    + cfg.playbackLogOverwrite( void ) : bool
    + cfg.getStreamTimeoutVal( void ) : int
    + cfg.getNetworkTimeoutVal( void ) : int
    + cfg.getUIConfig( void ) : UIConfig_t
    + cfg.setUIConfig( const UIConfig_t * cfg ) : bool
}

@enduml