@startuml
'https://plantuml.com/class-diagram

allowmixing

class Settings {
    /* ... */
    ----
    - io_libs.sys_lib_path : const char *;
    - io_libs.player.dir_name : const char *
    - io_libs.player.dflt_name : const char *
    - io_libs.player.name : String_t
    - io_libs.sound_server.dir_name : const char *
    - io_libs.sound_server.dflt_name : const char *
    - io_libs.sound_server.name : String_t
    ====
    /* ... */
    ----
    <b>Plugins</b>
    ----
    + plugins.getAudioServer( void ) : AudioOut_t
    + plugins.getPlayer void ) : Player_t
    ----
    /* ... */
}

class Plugin {
    - audio_server_initialised : bool
    - audio_server : AudioOut_t
    - player_initialised : bool
    - player : Player_t
    ====
    + loadAudioOut( const char * dir_path, const char * name ) : AudioOut_t *
    + loadPlayer( const char * dir_path, const char * name ) : Player_t *
    + free( void ) : void
}

package "player plugins" #white {
    file "ffmpeg.so" as pl_ffmpeg
}

package "output plugins" #white {
    file "pulse.so" as pl_pulse
    file "sdl.so" as pl_sld
    file "alsa.so" as pl_alsa
}

Plugin .[#RoyalBlue].> pl_sld
Plugin .[#RoyalBlue].> pl_pulse
Plugin .[#RoyalBlue].> pl_alsa
Plugin .[#RoyalBlue].> pl_ffmpeg

Settings --> Plugin




@enduml