@startuml
'https://plantuml.com/component-diagram

interface "Radio Stream" as RadioStream #back:black;line:black
interface "Sound out" as out #back:black;line:black

component "Driver\n(main)" as Controller #back:gold;line:black

package network #lightgrey {
    interface "Radio Browser API" as RadioBrowserAPI
    interface "Radio Browser web API" as RadioBrowserAPI
    interface "OpenSSL lib"           as OpenSSL
    interface "Sockets lib"           as Sockets
    component NetworkUtils
    component RadioBrowser

    NetworkUtils --( OpenSSL : "uses"
    NetworkUtils --( Sockets : "uses"
    OpenSSL      ..> RadioBrowserAPI : https
    Sockets      ..> RadioBrowserAPI : http/dns

    RadioBrowser -left-> NetworkUtils
    NetworkUtils <.[#black]right. RadioBrowser : query
    NetworkUtils .[#black]right.> RadioBrowser : string\n(raw data)
}

package parser #lightgrey {
    component JSON
    interface JSONlib as "json-c lib"

    JSON --( JSONlib : uses
}

RadioBrowser -->              JSON
RadioBrowser .[#black]down.>  JSON : string\n(raw data)
JSON         .[#black]up..>   RadioBrowser : DTO(s)

package player #lightgrey {
    component RadioPlayer
    component SDL
    interface "AudioOut interface" as iAudioOut

    iAudioOut -- SDL
    RadioPlayer --( iAudioOut
    RadioPlayer .[#black]right.> SDL : PCM data
}

Controller -down-> RadioBrowser
Controller -down-> RadioPlayer

RadioBrowser .[#black]right.> RadioPlayer : DTO(s)\n(radio station)

RadioStream .[#black].> RadioPlayer
SDL .[#black].> out

@enduml